apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
        - name: feed
          image: ghcr.io/your-org/feed:latest
          ports:
            - containerPort: 80
          env:
            - name: SUPABASE_URL
              value: https://your-supabase-url
            - name: SUPABASE_ANON_KEY
              value: your-supabase-anon-key
---
apiVersion: v1
kind: Service
metadata:
  name: feed
spec:
  selector:
    app: feed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
